### ISSUE TITLE
Containing DRM Protection and can't be downloaded - WON'T FIX!

### ISSUE THREAD

**Issue by crema-git** [heliomarpm/udemy-downloader-gui#13]
![image](https://user-images.githubusercontent.com/60826229/147539509-73e081e1-6974-4219-97ed-583e73298602.png)
is there any solution for this issue?

**Comment by heliomarpm** [comment]
Unfortunately doesn't have a solution to that

**Comment by rushikeshs187** [comment]
common there must be something

**Comment by heliomarpm** [comment]
> 



> comum deve haver algo
You can try this
https://github.com/Puyodead1/udemy-downloader

**Comment by heliomarpm** [comment]
This problem will not be fixed.

Udemy has started encrypting many of the course videos, so downloading them may be impossible/illegal because it involves decrypting DRM videos that open the author to DMCA removals/legal proceedings.

If you have a decryption key, at your own risk, you can find a solution in the repository 👇.
https://github.com/Puyodead1/udemy-downloader
