### ISSUE TITLE
Autop bug in downloading the video

### ISSUE THREAD

**Issue by NTWPanda** [heliomarpm/udemy-downloader-gui#40]
The files are getting downloaded but the downloaded files are not able to play because the video files is not complete size. Some are getting downloaded without an issue but a lot of the content are having this issue when I check in the udeler while downloading it says "autop" and the files immediately downloads. The files that shows their resolution are playing without an issue. Please fix it.

**Comment by heliomarpm** [comment]
These files are encrypted, there is nothing to fix

**Comment by Christian-Martinez1** [comment]
@heliomarpm Is it possible for only some of the videos to be DRM protected though, or is it normally the whole course? Because some of the lessons download fine as he mentioned above, but some of the videos I get the same autop issue. I would think if the course was DRM protected then the whole course would be, right?

**Comment by Christian-Martinez1** [comment]
I see, thanks for the confirmation!

**Comment by heliomarpm** [comment]
This issue is duplicate, please comment in #13
