### ISSUE TITLE
Containing DRM Protection and can't be downloaded

### ISSUE THREAD

**Issue by mabdulmoez** [heliomarpm/udemy-downloader-gui#51]
### Udeler | Udemy Course Downloader

"1.11.2"

### Running as Business Account

- [X] Yes

### Steps to reproduce

Trying to download a course and it says that contains RDM protection and can't be downloaded.

### ✔️ Expected Behavior

![image](https://user-images.githubusercontent.com/45119568/168088317-57c5704b-41de-47c4-ba51-0cba75e4f326.png)

### ❌ Actual Behavior

![image](https://user-images.githubusercontent.com/45119568/168088067-6a74204a-3741-49d2-948a-823dcdbd2d6b.png)

**Comment by heliomarpm** [comment]
This problem will not be fixed.

Udemy has started encrypting many of the course videos, so downloading them may be impossible/illegal because it involves decrypting DRM videos that open the author to DMCA removals/legal proceedings.

If you have a decryption key, at your own risk, you can find a solution in the repository 👇.
https://github.com/Puyodead1/udemy-downloader
